import 'package:flutter/material.dart';
class HomePage extends StatefulWidget{
  static final String id='home_page';
  @override
  _HomePageState createState()=>_HomePageState();
}
class _HomePageState extends State<HomePage>{
  @override
  Widget build(BuildContext context){
    return Scaffold(
      backgroundColor:Colors.white,
      appBar:AppBar(
        title:Text('Cars',style:TextStyle(color:Colors.black,fontSize:30),),
        backgroundColor:Colors.white,
        bottomOpacity:0.0,
        elevation:0.0,
        brightness:Brightness.light,
        centerTitle:false,
        leading:null,
        actions:[
          IconButton(
            icon:Icon(Icons.notifications_none_outlined,size:25),
            color:Colors.black,
            onPressed:(){
            },
          ),
          IconButton(
            icon:Icon(Icons.shopping_cart_rounded,size:25),
            color:Colors.black,
            onPressed:(){
            },
          ),
        ],
      ),
      body:SingleChildScrollView(
        child:Container(
          padding:EdgeInsets.all(15),
          child:Column(
            children:[
            Container(
              height:40,
              child:ListView(
                scrollDirection:Axis.horizontal,
                children:[
                  _listItems(true,'All'),
                  _listItems(false,'Red'),
                  _listItems(false,'Blue'),
                  _listItems(false,'Green'),
                  _listItems(false,'Yellow'),
                ],
              ),
            ),
              SizedBox(height:15),
              makeCar('assets/images/im_car1.jpg'),
              makeCar('assets/images/im_car2.jpg'),
              makeCar('assets/images/im_car3.jpg'),
              makeCar('assets/images/im_car4.png'),
              makeCar('assets/images/im_car5.jpg'),
            ],
          ),
        ),
      ),
    );
  }
  Widget _listItems(bool type,String text){
    return AspectRatio(
      aspectRatio:2.5/1,
      child:Container(
        margin:EdgeInsets.only(right:10),
        decoration:BoxDecoration(
          borderRadius:BorderRadius.circular(20),
          color:type ?Colors.grey[200]:Colors.white,
        ),
        child:Center(
          child:Text(text,style:TextStyle(fontSize:type?20:17,color:Colors.black45,),),
        ),
      ),
    );
  }
  Widget makeCar(String image){
   return Container(
     height:250,
     width:double.infinity,
     margin:EdgeInsets.only(bottom:20),
     decoration:BoxDecoration(
       borderRadius:BorderRadius.circular(25),
       image:DecorationImage(
         image:AssetImage(image),
         fit:BoxFit.cover,
       ),
       boxShadow:[
         BoxShadow(color:Colors.grey[400],blurRadius:10,offset:Offset(0,10)),
       ],
     ),
     child:Container(
       padding:EdgeInsets.all(20),
       height:250,
       width:double.infinity,
       decoration:BoxDecoration(
         borderRadius:BorderRadius.circular(25),
         gradient:LinearGradient(
           begin:Alignment.bottomRight,
           colors:[
             Colors.black.withOpacity(0.5),
             Colors.black.withOpacity(0.4),
             Colors.black.withOpacity(0.3),
             Colors.black.withOpacity(0.2),
           ],
         ),
       ),
       child:Row(
         crossAxisAlignment:CrossAxisAlignment.stretch,
         children:[
           Expanded(
             flex:6,
             child:Container(
               child:Column(
                 mainAxisAlignment:MainAxisAlignment.spaceBetween,
                 crossAxisAlignment:CrossAxisAlignment.start,
                 children:[
                   Column(
                     crossAxisAlignment:CrossAxisAlignment.start,
                     children:[
                       Text('PDP Car',style:TextStyle(fontSize:27,color:Colors.white,fontWeight:FontWeight.w500,),),
                       SizedBox(height:15),
                       Text('Electric',style:TextStyle(fontSize:20,color:Colors.white,fontWeight:FontWeight.w500),),
                     ],
                   ),
                   Text('100\$',style:TextStyle(fontSize:23,fontWeight:FontWeight.bold,color:Colors.white,)),
                 ],
               ),
             ),
           ),
           Expanded(
             flex:1,
             child:Container(
               child:Column(
                 crossAxisAlignment:CrossAxisAlignment.end,
                 children:[
                   Container(
                     height:35,
                     width:35,
                     decoration:BoxDecoration(
                       shape:BoxShape.circle,
                       color:Colors.white,
                     ),
                     child:Icon(Icons.favorite_border,color:Colors.black,),
                   ),
                 ],
               ),
             ),
           ),
         ],
       ),
     ),
   );
  }
}